import{S as d,i as n}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const f=document.querySelector(".form"),c=document.querySelector(".searchInput");document.querySelector(".searchButton");const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),m="51442110-4fde2839a6cf4cc45b6823f02";let p=new d(".gallery a.gallery-link",{navText:["❮","❯"],captionsData:"alt",captionDelay:250,captionPosition:"bottom",close:!0,closeText:"×",animationSlide:!0,animationSpeed:250,enableKeyboard:!0,overlay:!0,overlayOpacity:.8,sourceAttr:"href",zoom:!1});function h(){u.classList.add("is-hidden")}function g(){u.classList.remove("is-hidden")}function y(s){return s.map(r=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
            </a>
            <div class="image-info">
                <p class="info"><b>Likes</b>${r.likes}</p>
                <p class="info"><b>Views</b>${r.views}</p>
                <p class="info"><b>Comments</b>${r.comments}</p>
                <p class="info"><b>Downloads</b>${r.downloads}</p>
            </div>
        </li>`).join("")}f.addEventListener("submit",s=>{s.preventDefault();const r=c.value.trim();if(r===""){n.error({message:"Please enter a search term.",position:"topRight",backgroundColor:"#EF4040",messageColor:"white",progressBarColor:"#B51B1B",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"});return}l.innerHTML="",g();const a=new URLSearchParams({key:m,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${a}`).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()}).then(t=>{const e=t.hits;if(e.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"white",progressBarColor:"#B51B1B",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"});return}l.innerHTML=y(e),p.refresh()}).catch(t=>{n.error({title:"Error",message:`An error occurred while fetching images: ${t.message}`,position:"topRight"}),console.error("Error fetching images:",t)}).finally(()=>{h(),c.value=""})});
//# sourceMappingURL=index.js.map
